version: "3"
services:
  app:
    container_name: curriculum-front
    build:
      context: ../curriculum-front
      args:
        - VUE_APP_API_URL=http://localhost:5050
    networks:
      - curriculum_network
    depends_on:
      - api
      - db
    ports:
      - "8080:8080"
  api:
    container_name: curriculum-back
    build:
      context: ../curriculum-back
      dockerfile: ${API_DOC_FILE:-Dockerfile}
    networks:
      - curriculum_network
    depends_on:
      - db
  db:
    container_name: mongo
    image: mongo:4.2.0-bionic
    volumes:
      - /data/db:/data/db
    networks:
      - curriculum_network
networks:
  curriculum_network:
    driver: bridge
